title: "FAM - Ferramenta de Acreditação Militar"
author: "MDS Grupo 2"
description: "Auxílio na avaliação e certificação de Organizações de Saúde Militar"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true         # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}
  - {file: "tap.md"}
  
produto:
  - {file: "2021-09-10-arquitetura.md", title: Arquitetura}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/fga-eps-mds/2021-1-hospitalar"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
